### ISSUE TITLE
Duplicate alpha-2 code

### ISSUE THREAD

**Issue by NorbertHuethmayr** [ilyabreev/Bia.Countries#10]
The ISO 3166 alpha-2 code for "SJ" is present twice. 

One time for a country called **Svalbard** and another one for a country called **Svalbard and Jan Mayen**. According to the standard the abbreviation "SJ" refers to "Svalbard and Jan Mayen". When performing a lookup for "SJ" the library returns "Svalbard" without a alpha 3 code.

**Comment by ilyabreev** [comment]
Could you please provide sample code to reproduce the problem?

**Comment by NorbertHuethmayr** [comment]
Hi Ilya,

I dont have a notebook with me at the moment but reproducing is really easy.

Just take the language code SJ and call GetCountrByAlpha2() the result is
an object which does not have the alpha 3 code set.

If you look further at the class CountryList.cs you will see that there are
2 instances of Iso3166Country that have the 2letter code set.

If that description is not enough I will provide a sample tmr morning.

Best regards
Norbert


On Thu, 16 Mar 2017 at 18:06, Ilya Breev <notifications@github.com> wrote:

Could you please provide sample code to reproduce the problem?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/ilyabreev/Bia.Countries/issues/10#issuecomment-287125245>,
or mute the thread

**Comment by ilyabreev** [comment]
@NorbertHuethmayr many thanks for report. I'll try to bump fresh nuget package tomorrow morning.

**Comment by ilyabreev** [comment]
@NorbertHuethmayr Here we go. https://www.nuget.org/packages/Bia.Countries/2.0.1
