### ISSUE TITLE
Move Iso3166 prefix into namespace

### ISSUE THREAD

**Issue by zaha** [ilyabreev/Bia.Countries#12]
Hey,

I really like your library. Only thing that bothers me is the `Iso3166 ` prefix before every class: I think this would be better placed in the namespace. Would lead to less redundancy and nicer names :)

Kind regards
Michael

**Comment by ilyabreev** [comment]
Hey!

Glad to hear that my library helps you.
Your suggestion looks good. I'll try to bump the fix as soon as possible.

**Comment by ilyabreev** [comment]
@zaha looks nicer, huh?

**Comment by zaha** [comment]
@ilyabreev Looks sleek, I like it! 👍 
Thanks for the quick response.

**Comment by zaha** [comment]
Hey @ilyabreev,

quick question: When will publish the package with this change to nuget?

Cheers
Michael

**Comment by ilyabreev** [comment]
Hi!

On the week.
пн, 8 мая 2017 г. в 16:32, Michael Barth <notifications@github.com>:

**Comment by ilyabreev** [comment]
@zaha Just pushed v2.0.2 to NuGet. It'll appear soon.
