### ISSUE TITLE
Introduce country code enum for static type safety

### ISSUE THREAD

**Issue by zaha** [ilyabreev/Bia.Countries#13]
Hey @ilyabreev,

what do you think of the idea to add a  country code enum instead of relying on string? This would add static type safety when working with them as parameters or variables.

Of course, parsing string country codes should be kept, too.

There's [another library on github here](https://github.com/MaddalenaTech/Countries/blob/master/Countries/Country.cs) that does something similar. Tried that before using yours :)

Kind regards
Michael

**Comment by ilyabreev** [comment]
Good idea.
Can you make a PR?

**Comment by zaha** [comment]
I'm rather busy right now but I'll see if I can get this done in the coming weeks. :)

**Comment by zaha** [comment]
Just to give you a heads up: I currently waiting for my organization to setup a Github org where I can fork this to. As soon as that's done, I'll create the pull request.

As far as I heard, this should happen in the next 2 weeks.

**Comment by ilyabreev** [comment]
Glad to hear that!
пт, 9 июня 2017 г. в 15:55, Michael Barth <notifications@github.com>:
