### ISSUE TITLE
Powershell Gallery - Bia.Countries 1.0

### ISSUE THREAD

**Issue by LaurentDardenne** [ilyabreev/Bia.Countries#14]
Hi,
the actual package on PSGallery is it up to date ?

**Comment by ilyabreev** [comment]
I don't think so.
@KeeperB5 manages the powershell part of the project.

**Comment by LaurentDardenne** [comment]
Thanks

**Comment by KeeperB5** [comment]
Sorry it took me a while to answer to this. I don't actively follow Bia.Countries project so changes to the project may go unnoticed. I'll look into updating the PowerShell module at PSGallery.
