### ISSUE TITLE
Query about docs

### ISSUE THREAD

**Issue by space-alien** [ilyabreev/Bia.Countries#18]
> The library also includes country names as seen in Microsoft Active Directory Users and Computers (ADUC) on Windows Server 2012 R2. Several countries were added to the library that do not exist in, or have since been removed from ISO-3166-1. Such countries will have only ActiveDirectoryName, Alpha2 and Numeric properties. ShortName, FullName and Alpha3 properties are null to prevent them from appearing in most queries targeted for ISO-3166-1.

From scanning the data, it looks to me like these countries also lack the Alpha2 property, and only have ActiveDirectoryName and Numeric properties.

**Comment by ilyabreev** [comment]
Yeah that's because... They doesn't exist in ISO :-)

**Comment by space-alien** [comment]
Yes :) but the docs imply that these particular countries will have an Alpha2 property (but they never will).
