### ISSUE TITLE
United Kingdom

### ISSUE THREAD

**Issue by ichpuchtli** [ilyabreev/Bia.Countries#3]
I can't find United Kingdom on the official ISO standard. Only ```United Kingdom of Great Britain and Northern Ireland (the)```

See https://www.iso.org/obp/ui/#iso:code:3166:GB

**Comment by ilyabreev** [comment]
Thank you for your bug report!
Fixed in   https://github.com/ilyabreev/Bia.Countries/commit/01346cc6a9d538653c49b6a0bfd9c6b5ed2debbb

Fixed package will be available soon at https://www.nuget.org/packages/Bia.Countries/1.2.0
