### ISSUE TITLE
Strongly typed

### ISSUE THREAD

**Issue by cyberprune** [ilyabreev/Bia.Countries#9]
Hello, can you please sign the dll in the NuGet package or release a strongly typed version. This project doesn't work when Code Analysis is running. Thanks!

**Comment by ilyabreev** [comment]
Added assembly signing at 2811ded681a01d2d0d74c6535a0e3a27b57967bb
Is it sufficient to work with Code Analysis?

**Comment by ilyabreev** [comment]
Suppose it is enough.
